# fly.toml app configuration file generated for api-patient-sunset-7048 on 2024-11-17T22:33:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-patient-sunset-7048'
primary_region = 'yul'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  APP_RUNTIME = '\App\FlySymfonyRuntime'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1
